DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER(ID INT PRIMARY KEY, FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255), ADDRESS VARCHAR(255), MODIFIED_DATE_TIME TIMESTAMP);
SELECT * FROM CUSTOMER

INSERT INTO CUSTOMER VALUES(1, 'Elan','Mask','28GeorgeST,NSW,2000,AU', CURRENT_TIMESTAMP);

INSERT INTO CUSTOMER VALUES(2, 'Steve','Jobs','98SmithST,VIC,3000,AU', CURRENT_TIMESTAMP);

INSERT INTO CUSTOMER VALUES(3, 'Zuckerberg','Mark','82TargoRD,NSW,2010,AU', CURRENT_TIMESTAMP);